site_name: HPC Documentation

use_directory_urls: false
nav:
  - Announcements: general/news.md
  - Getting Started: 
    - About the clusters: getting-Started/about-clusters.md
    - Prerequisites: 
      - MSKCC HPC system "LILAC": getting-Started/lilac-overview.md
      - Account Creation and Activation: getting-Started/account.md
      - SSH customization: getting-Started/ssh-customization.md
        ## ssh clients
      - Shell customization: getting-Started/shell.md
        ## shell scripting
      - Unix/Linux Resources: getting-Started/unix-linux.md
    - Accessing the Clusters: 
      #      - software for connecting to the HPCs: getting-Started/login-ssh.md
      #      - Port Forwarding:
        - Via Command Line: getting-Started/command-line.md
        - Via Web Browser: getting-Started/web-browser.md
          # - OnDemand: 
    - Bringing Data Into the Cluster: getting-Started/bring-data.md
    - LSF and Submitting jobs: lsf/submission.md
    - LSF Glossary: lsf/lsf-glossary.md  
    # For more info: link to Running jobs*
  - User Guide:
    - Running Interactive Jobs: lsf/interactive-jobs.md
    - Partitions / QoS: lsf/partitions.md
    - Monitoring Jobs: lsf/monitoring-jobs.md
    - Deleting Jobs: lsf/deleting-jobs.md
    - Array Jobs with lsf: lsf/array-jobs.md
    - Job dependencies: lsf/dependencies.md
    - GPUs: lsf/gpus.md
    - Investigating a Job Failure: lsf/investigating-job-failure.md
    - Checkpointing: lsf/checkpointing.md
    - Fair Share: lsf/fair-share.md
    #
  - Software:
    - HPC software environment: software/hpc-modules.md
    - Installing Custom Software: software/installing-custom-software.md
    - EasyBuild: software/EasyBuild.md
    - Supported Applications:
      - Anaconda: software/Anaconda.md
      - CUDA: software/CUDA.md
      - JupyterLab: software/JupyterLab.md
      - Matlab: software/matlab.md
      - Parallel BZIP2: software/bzip2.md
      - ParaView: software/ParaView.md
      - Python: software/python.md
      - R: software/r.md
      - Relion: software/relion.md
      - Singularity: software/singularity.md
  - Storage:
    - Overview: file-system/filesystem-overview.md
    - Quota: file-system/quota.md
    - Moving files to and from the HPCs: file-system/file-transfer.md
    - Scratch: file-system/scratch.md
  - Workspaces: 
    - Intro to Workspaces: getting-Started/workspaces.md
    - Overview: hpc-workspaces/workspaces.md
    - Workspace management: hpc-workspaces/management.md
    - Software environment: hpc-workspaces/environment.md
    - Monitoring: hpc-workspaces/monitoring.md
  - Optimization:
    - Scaling: optimization/scaling.md
  - Investment: general/investment.md
  - Support: general/support.md
  - FAQ: general/faq.md
  - Hall of Fame: halloffame.md
  - Code of Conduct: code-of-conduct.md
  - Glossary: getting-Started/glossary.md


# Copyright footer
copyright: 'Copyright &copy; Memorial Sloan Kettering Cancer Center, High Performance Computing Group'
# Link to repo
repo_name: 'HPC/userdocs'
repo_url: 'https://github.mskcc.org/HPC/userdocs.git'
edit_uri: 'edit/main/docs'
site_dir: 'docs'
docs_dir: 'docs-src'

# Configuration
theme:
  name: material

extra_css:
 - 'stylesheets/mskcc.css'

plugins:
  - git-revision-date
  - search

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty
  - tables
  - toc

# Social links bottom right
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.mskcc.org/HPC/userdocs.git


