site_name: HPC Documentation

use_directory_urls: false
nav:
  - Announcements: general/news.md
  - Quick Start: quick-start.md
  - Getting Started:
    - Code of Conduct: code-of-conduct.md
    - MSKCC HPC system "LILAC": getting-Started/ubelix-overview.md
    - Accounts and Activation: getting-Started/account.md
    - Accessing the HPCs: getting-Started/login-ssh.md
      #      - software for connecting to the HPCs:
      #      - Port Forwarding:
    - Workspaces: getting-Started/workspaces.md
    - SSH customization: getting-Started/ssh-customization.md
    - Shell customization: getting-Started/shell.md
    - Parallelization: getting-Started/parallelization.md
  - Workspaces:
    - Overview: hpc-workspaces/workspaces.md
    - Workspace management: hpc-workspaces/management.md
    - Software environment: hpc-workspaces/environment.md
    - Monitoring: hpc-workspaces/monitoring.md
  - LSF / Job handling:
    - Partitions / QoS: slurm/partitions.md
    - Submitting jobs: slurm/submission.md
    #      - Parallel execution:
    - Monitoring Jobs: slurm/monitoring-jobs.md
    - Deleting Jobs: slurm/deleting-jobs.md
    - Array Jobs with Slurm: slurm/array-jobs.md
    - Job dependencies: slurm/dependencies.md
    - GPUs: slurm/gpus.md
    - Interactive Jobs: slurm/interactive-jobs.md
    - Investigating a Job Failure: slurm/investigating-job-failure.md
    - Checkpointing: slurm/checkpointing.md
    - Fair Share: slurm/fair-share.md
    #
  - Software:
    - HPC software environment: software/hpc-modules.md
    - Installing Custom Software: software/installing-custom-software.md
    - EasyBuild: software/EasyBuild.md
    - Supported Applications:
      - Anaconda: software/Anaconda.md
      - CUDA: software/CUDA.md
      - JupyterLab: software/JupyterLab.md
      - Matlab: software/matlab.md
      - Parallel BZIP2: software/bzip2.md
      - ParaView: software/ParaView.md
      - Python: software/python.md
      - R: software/r.md
      - Relion: software/relion.md
      - Singularity: software/singularity.md
      - Terminal Multiplexer (tmux): software/terminal-multiplexer-tmux.md
  - Storage:
    - Overview: file-system/filesystem-overview.md
    - Quota: file-system/quota.md
    - Moving files to and from the HPCs: file-system/file-transfer.md
    - Scratch: file-system/scratch.md
  - Optimization:
    - Scaling: optimization/scaling.md
  - Investment: general/investment.md
  - Support: general/support.md
  - FAQ: general/faq.md
  - Hall of Fame: halloffame.md
  - Code of Conduct: code-of-conduct.md


# Copyright footer
copyright: 'Copyright &copy; Memorial Sloan Kettering Cancer Center, High Performance Computing Group'
# Link to repo
repo_name: 'HPC/userdocs'
repo_url: 'https://github.mskcc.org/HPC/userdocs.git'
edit_uri: 'edit/main/docs'
site_dir: 'docs'
docs_dir: 'docs-src'

# Configuration
theme:
  name: material

extra_css:
 - 'stylesheets/mskcc.css'

plugins:
  - git-revision-date
  - search

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty
  - tables
  - toc

# Social links bottom right
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.mskcc.org/HPC/userdocs.git

